name: Feature Request
description: Suggest a new feature or enhancement for Aura
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Aura? We'd love to hear it. Please describe what you'd like and why.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: "Which part of Aura does this relate to?"
      options:
        - Mood Engine (detection, signals, zones)
        - Theming (colors, transitions, visual effects)
        - Terminal (rendering, input, PTY)
        - Claude Code Integration (hooks, mood injection)
        - Side Panel (orb, stats, timeline)
        - Configuration
        - CLI / UX
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: "What problem does this solve, or what does it enable?"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "How do you envision this working?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you considered any other approaches?"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Screenshots, mockups, links, or anything else"
